spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true

logging:
  level:
    com.hotel.operacloud: INFO
    org.springframework.kafka: WARN
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    liquibase: DEBUG
