package com.hotel.operacloud.persistence.financial;

import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Data
public class FinancialTransactionRecord {

    private String operation;
    private Long trxNo;
    private BigDecimal arLedCredit;
    private BigDecimal arLedDebit;
    private String arState;
    private Long arrangementId;
    private Long billNo;
    private LocalDate businessDate;
    private BigDecimal cashierCredit;
    private BigDecimal cashierDebit;
    private Long cashierId;
    private String chequeNumber;
    private String currency;
    private BigDecimal depLedCredit;
    private BigDecimal depLedDebit;
    private BigDecimal exchangeRate;
    private Long finDmlSeqNo;
    private Long folioNo;
    private String folioType;
    private Long folioView;
    private Long fromResvId;
    private String ftSubtype;
    private BigDecimal grossAmount;
    private BigDecimal guestAccountCredit;
    private BigDecimal guestAccountDebit;
    private LocalDateTime insertDate;
    private Long insertUser;
    private LocalDate invoiceCloseDate;
    private Long invoiceNo;
    private String invoiceType;
    private String marketCode;
    private Long membershipId;
    private Long nameId;
    private BigDecimal netAmount;
    private String numberDialed;
    private BigDecimal orgPostedAmount;
    private Long originalResvNameId;
    private BigDecimal packageAllowance;
    private String packageArrangementCode;
    private BigDecimal packageCredit;
    private BigDecimal packageDebit;
    private BigDecimal postedAmount;
    private LocalDate postingDate;
    private String postingType;
    private BigDecimal pricePerUnit;
    private BigDecimal quantity;
    private String rateCode;
    private Long receiptNo;
    private String receiptType;
    private String reference;
    private String remark;
    private String resort;
    private Long resvNameId;
    private BigDecimal revenueAmt;
    private String room;
    private String roomClass;
    private Long routingInstrnId;
    private String sourceCode;
    private String taCommissionableYn;
    private String targetResort;
    private String taxGeneratedYn;
    private String taxInclusiveYn;
    private String tcGroup;
    private String tcSubgroup;
    private Long tranActionId;
    private BigDecimal trxAmount;
    private String trxCode;
    private LocalDate trxDate;
    private Long trxNoAddedBy;
    private Long trxNoAdjust;
    private Long trxNoAgainstPackage;
    private Long trxNoSplit;
    private LocalDateTime updateDate;
    private Long updateUser;
    private BigDecimal cashierOpeningBalance;
    private String hotelAcct;
    private String originalRoom;
    private Long resvDepositId;
    private String sourceCommissionNetYn;
    private Long toResvNameId;
    private Long trxNoHeader;
    private String packageTrxType;
    private String taCommissionNetYn;
}
